name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bump_and_tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Tag & Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver.outputs.nextStrict }}

    outputs:
      version: ${{ steps.bump-version.outputs.newTag }}

  deploy_to_infra:
    runs-on: ubuntu-latest
    needs: bump_and_tag
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Create deployment
        run: doctl apps create-deployment 7a504892-fbac-4ee8-ba3b-6e300aec5c20
